name: beng203
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - pre-commit
  - matplotlib
  - seaborn
  - ruff
  - ipykernel
  - openpyxl
  - scikit-learn
  - jupyter
  - pip
  - pip:
    - rnanorm

